psi_pretraining:
  pretrained_path: pretrained/
  overwrite: True

  train_jsonl_path: /Users/Yaroslav.Sokolov/work/psi_data/java_small_out/java_small_out.val.jsonl
#  train_jsonl_path: /Users/Yaroslav.Sokolov/work/psi_data/java_small_out/java_small_out.train.jsonl
#  train_jsonl_path: /Users/Yaroslav.Sokolov/work/psiminer/mock_data/mock_data.train.jsonl

  transformations:
    - whitespace_normalize

  tokenizer:
    vocab_size: 16384
    min_frequency: 100
    dropout: 0

